# Generated by Django 4.2.28 on 2026-02-26 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('city_code', models.CharField(choices=[('NYC', 'New York City'), ('LA', 'Los Angeles'), ('SF', 'San Francisco')], max_length=8)),
                ('result_grade', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('UNDETERMINED', 'Undetermined')], default='UNDETERMINED', max_length=16)),
                ('decision_mode', models.CharField(choices=[('AUTO_CONFIDENT', 'Auto Confident'), ('AUTO_CONSERVATIVE', 'Auto Conservative')], default='AUTO_CONSERVATIVE', max_length=32)),
                ('blocker_flags', models.JSONField(default=list)),
                ('required_actions', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutonomyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('trigger', models.CharField(max_length=128)),
                ('action_taken', models.CharField(max_length=255)),
                ('outcome', models.CharField(max_length=64)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('plan', models.CharField(default='starter', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RollbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_release', models.CharField(max_length=128)),
                ('fallback_release', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('recovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SLOMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=64)),
                ('metric_value', models.FloatField(default=0.0)),
                ('target_value', models.FloatField(default=0.0)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('window_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='healthy', max_length=16)),
            ],
            options={
                'ordering': ['-window_end'],
            },
        ),
        migrations.CreateModel(
            name='RuleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_code', models.CharField(choices=[('NYC', 'New York City'), ('LA', 'Los Angeles'), ('SF', 'San Francisco')], max_length=8)),
                ('version', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STALE', 'Stale'), ('FAILED', 'Failed')], default='ACTIVE', max_length=16)),
                ('validation_score', models.FloatField(default=0.0)),
                ('source_urls', models.JSONField(default=list)),
                ('parsed_payload', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('city_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('report', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_imports', to='permitpulse.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_ids', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address_check', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_trace', to='permitpulse.addresscheck')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_traces', to='permitpulse.rulesnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPolicyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(max_length=64)),
                ('policy_id', models.CharField(max_length=64)),
                ('input_event', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_actions', to='permitpulse.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='permitpulse.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_code', models.CharField(choices=[('NYC', 'New York City'), ('LA', 'Los Angeles'), ('SF', 'San Francisco')], max_length=8)),
                ('change_type', models.CharField(max_length=64)),
                ('impacted_listing_ids', models.JSONField(default=list)),
                ('severity', models.CharField(default='medium', max_length=16)),
                ('message', models.TextField()),
                ('status', models.CharField(default='new', max_length=16)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='permitpulse.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='addresscheck',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_checks', to='permitpulse.organization'),
        ),
        migrations.AddField(
            model_name='addresscheck',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_checks', to='permitpulse.rulesnapshot'),
        ),
        migrations.CreateModel(
            name='RuleClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_id', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('condition_expr', models.JSONField(default=dict)),
                ('requirement_text', models.TextField()),
                ('penalty_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='permitpulse.rulesnapshot')),
            ],
            options={
                'unique_together': {('snapshot', 'clause_id')},
            },
        ),
    ]
